### ISSUE TITLE
Add player node

### ISSUE THREAD

**Issue by ApGoldberg** [ljhs-games/week-76#6]
Should be Area2D (?) that spawns a bullet when clicked. Sprite should be a miniature sniper scope.

**Comment by creikey** [comment]
Node should not be an area2D, just a sprite node with a light2d as a child. When there's a click, should instance a new bullet node then call `fire(global_position` on the newly childed bullet node

**Comment by creikey** [comment]
Before firing, should check with the `GameState` node if ready to fire

**Comment by creikey** [comment]
As stated in #12, should subscribe to a signal in `GameState` for when it should increase in size
